galaxy_info:
  author: Cenk Kilic
  description: manage ssl certificates, and inject them to a given repository
  company: kilic.dev
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Alpine
      versions:
        - all

dependencies: []
