- name: concatenate public keys
  when:
    - authorized_key is not defined
  set_fact:
    keys: "{{ (keys | default('')) + lookup('file', item) + '\n' }}"
  with_fileglob:
    - '{{ authorized_keys_root }}/*.pub'

- name: copy authorized_keys
  when:
    - authorized_key is not defined
  authorized_key:
    user: '{{ ansible_management_user }}'
    key: '{{ keys }}'
    state: present
    exclusive: true

- name: set fact for defined authorized_key
  when:
    - authorized_key is defined
  set_fact:
    auth_keys: "{{ (auth_keys | default('')) + lookup('file', item) + '\n' }}"
  with_fileglob:
    - "{{ authorized_keys_root }}/({{ authorized_key | join('|') }}).pub"

- name: append authorized key from file
  when:
    - authorized_key is defined
    - authorized_key_replace != true
    - authorized_key_remove != true
  authorized_key:
    user: '{{ ansible_management_user }}'
    state: present
    key: '{{ auth_keys }}'

- name: set authorized key from file
  when:
    - authorized_key is defined
    - authorized_key_replace == true
    - authorized_key_remove != true
  authorized_key:
    user: '{{ ansible_management_user }}'
    state: present
    exclusive: true
    key: '{{ auth_keys }}'

- name: gtfo authorized key from file
  when:
    - authorized_key is defined
    - authorized_key_remove == true
  authorized_key:
    user: '{{ ansible_management_user }}'
    state: absent
    key: '{{ auth_keys }}'
