---
- name: 'ensure target directory exists: {{ copy_files_dest }}'
  file:
    path: '{{ copy_files_dest }}'
    state: directory

- name: ensure directories in the tree exists in {{ copy_files_dest }}
  file:
    path: '{{ copy_files_dest }}/{{ file.path }}'
    state: directory
  with_items: '{{ copy_files_src_all_directories }}'
  loop_control:
    loop_var: file
  when:
    - copy_files_src_all_directories | length > 0
  changed_when: false

- name: copying files from {{ copy_files_src }}
  ansible.posix.synchronize:
    src: '{{ file.src }}'
    dest: '{{ copy_files_dest }}/{{ file.path }}'
  with_items: '{{ copy_files_src_files }}'
  loop_control:
    loop_var: file
  when:
    - copy_files_src_files | length > 0

- name: copying secrets from {{ copy_files_src }}
  copy:
    src: '{{ file.src }}'
    dest: '{{ copy_files_dest }}/{{ file.path | regex_replace(".secrets", "") }}'
    decrypt: true
  with_items: '{{ copy_files_src_secrets }}'
  loop_control:
    loop_var: file
  when:
    - copy_files_src_secrets | length > 0

- name: copying templates from {{ copy_files_src }}
  template:
    src: '{{ file.src }}'
    dest: '{{ copy_files_dest }}/{{ file.path | regex_replace(".secrets", "") | regex_replace(".j2$", "") }}'
  with_items: '{{ copy_files_src_templates }}'
  loop_control:
    loop_var: file
  when:
    - copy_files_src_templates | length > 0
