- name: ensure target directory exists
  file:
    path: '{{ copy_files_dest }}'
    state: directory

- name: copy files
  synchronize:
    src: '{{ item }}'
    dest: '{{ copy_files_dest }}/{{ item | regex_replace(".*/" + copy_files_src, "") | regex_replace(".secrets", "") }}'
  with_items: '{{ copy_files_src_files }}'

- name: copy templates
  template:
    src: '{{ item }}'
    dest: '{{ copy_files_dest }}/{{ item | regex_replace(".*/" + copy_files_src, "") | regex_replace(".secrets", "") | regex_replace(".j2$", "") }}'
  with_items: '{{ copy_files_src_templates }}'
