- name: scanning required files
  set_fact:
    copy_files_src_all: '{{ lookup("filetree", copy_files_src, wantlist=True) }}'

- name: filter directories
  set_fact:
    copy_files_src_all_directories: '{{ copy_files_src_all | selectattr("state", "==", "directory") }}'

- name: filter all files
  set_fact:
    copy_files_src_all_files: '{{ copy_files_src_all | selectattr("state", "==", "file") }}'

- name: filter files
  set_fact:
    copy_files_src_files: '{{ copy_files_src_all_files | rejectattr("path", "match", ".*\.j2$") | rejectattr("path", "match", ".*\.secrets.*") }}'

- name: filter secrets
  set_fact:
    copy_files_src_secrets: '{{ copy_files_src_all_files | rejectattr("path", "match", ".*\.j2$") | selectattr("path", "match", ".*\.secrets.*") }}'

- name: filter templates
  set_fact:
    copy_files_src_templates: '{{ copy_files_src_all_files | selectattr("path", "match", ".*\.j2$") }}'
