---
galaxy_info:
  author: Ted Cook
  description: An Ansible role to install and configure tmux
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Ubuntu
      versions:
        - xenial
    - name: Debian
      versions:
        - stretch
  galaxy_tags:
    - tmux

dependencies: []
