---
- name: debug
  debug:
    var: scmd_login_docker_registries_async_job
- name: debug
  debug:
    var: scmd_create_docker_networks_async_job
- name: wait for job to end
  ansible.builtin.async_status:
    jid: '{{ item.ansible_job_id }}'
    mode: status
  register: async_result
  until: async_result.finished
  retries: 100
  delay: 2
  with_items:
    - '{{ scmd_login_docker_registries_async_job.results if scmd_login_docker_registries_async_job else [] }}'
    - '{{ scmd_create_docker_networks_async_job.results if scmd_create_docker_networks_async_job else [] }}'
  notify:
    - start docker service
