---
- name: 'remove docker service: {{ scmd_service_name }}'
  community.docker.docker_compose:
    state: absent
    project_name: '{{ scmd_service_name }}'
    project_src: '{{ scmd_service_dir }}'
    remove_volumes: true
    remove_images: local
  ignore_errors: true

- name: remove docker setup
  file:
    path: '{{ scmd_loop_setup_dirs }}'
    state: absent
  when:
    - scmd_state is defined
    - scmd_state.setup is defined
    - scmd_state.setup == "absent"
  loop_control:
    loop_var: scmd_loop_setup_dirs
  with_items:
    - '{{ scmd_full_env_dir }}'
    - '{{ scmd_full_build_dir }}'
    - '{{ scmd_service_dir }}/docker-compose.yml'

- name: remove persistent docker volumes
  file:
    path: '{{ scmd_loop_all_dirs }}'
    state: absent
  with_items:
    - '{{ scmd_full_logs_dir }}'
    - '{{ scmd_full_volume_dir }}'
    - '{{ scmd_service_dir }}'
  loop_control:
    loop_var: scmd_loop_all_dirs
  when:
    - scmd_state is defined
    - scmd_state.all is defined
    - scmd_state.all == "absent"
