---
- name: pull images and restart service using docker service
  docker_compose:
    state: present
    project_name: '{{ scmd_service_name }}'
    project_src: '{{ scmd_service_dir }}'
    pull: true
    build: true
    remove_orphans: true
    recreate: always
    scale: '{{ scmd_scale | default({}) }}'
