---
- name: 'start docker service v2: {{ scmd_service_name }}'
  community.docker.docker_compose_v2:
    state: present
    project_name: '{{ scmd_service_name }}'
    project_src: '{{ scmd_service_dir }}'
    pull: always
    build: always
    remove_orphans: true
    recreate: always
    remove_volumes: '{{ scmd_remove_volumes | default(false) }}'
