---
- import_tasks: register-variables.yml
  when:
    - scmd_private_registry_only is not defined or not scmd_private_registry_only

- include_tasks: register-environment-variables.yml
  when:
    - scmd_variables_only is not defined or not scmd_variables_only
    - scmd_state is not defined

# - include_tasks: register-volume-directories.yml
#   when:
#     - scmd_variables_only is not defined or not scmd_variables_only
#     - scmd_state is not defined

- import_tasks: filesystem.yml
  when:
    - scmd_variables_only is not defined
    - scmd_private_registry_only is not defined
    - scmd_state is not defined

- import_tasks: generate-docker-compose-file.yml
  when:
    - scmd_variables_only is not defined or not scmd_variables_only
    - scmd_private_registry_only is not defined or not scmd_private_registry_only
    - scmd_state is not defined

- import_tasks: registry-login.yml
  when:
    - scmd_private_registry_only is defined and scmd_private_registry_only
    - scmd_private_registry is defined
    - scmd_external_network is not defined
    - scmd_state is not defined

- import_tasks: docker-network.yml
  when:
    - scmd_external_network is defined
    - scmd_external_network | length > 0
    - scmd_private_registry_only is not defined or not scmd_private_registry_only
    - scmd_state is not defined

- name: wait for job to end
  ansible.builtin.async_status:
    jid: '{{ item.ansible_job_id }}'
    mode: status
  register: async_result
  until: async_result.finished
  retries: 100
  delay: 2
  with_items:
    - '{{ scmd_login_docker_registries_async_job.results | default([]) if scmd_login_docker_registries_async_job.changed else [] }}'
    - '{{ scmd_create_docker_networks_async_job.results | default([]) if scmd_create_docker_networks_async_job.changed else [] }}'
  notify:
    - start docker service

- include_tasks: clean-up.yml
  when:
    - scmd_state is defined

- include_tasks: clean-up-variables.yml
  when:
    - scmd_variables_only is not defined or not scmd_variables_only
