---
- name: 'register volume directories: {{ scmd_service_name }}'
  set_fact:
    scmd_volume_dirs: |
      {% if 'volumes' in volume_dir and scmd_volume_dir in volume_dir.volumes %}
      {% set value = (scmd_volume_dirs | default([ ]) + [ '%s/%s' | format(scmd_full_volume_dir, scmd_service_name) ]) | unique %}
      {% else %}
      {% set value = scmd_volume_dirs | default([ ]) %}
      {% endif %}
      {{ value }}
  with_items:
    - '{{ scmd_services }}'
  loop_control:
    loop_var: volume_dir
  when:
    - scmd_services is defined

- name: 'volume directories: {{ scmd_service_name }}'
  debug:
    msg: '{{ scmd_volume_dirs }}'
  when:
    - ansible_check_mode
