---
- name: 'register volume directories: {{ scmd_service_name }}'
  set_fact:
    scmd_volume_dirs: |
      {% if 'volumes' in scmd_loop_services and scmd_volume_dir in scmd_loop_services.volumes %}
      {% set value = (scmd_volume_dirs | default([ ]) + [
        {
          "mount": "%s/%s" | format(scmd_full_volume_dir, scmd_service_name),
          "user": "%s" | format(scmd_loop_services.user | default(service_user)),
          "group": "%s" | format(scmd_loop_services.group | default(service_group))
        }
      ]) | unique %}
      {% else %}
      {% set value = scmd_volume_dirs | default([ ]) %}
      {% endif %}
      {{ value }}
  with_items:
    - '{{ scmd_services }}'
  loop_control:
    loop_var: scmd_loop_services
  when:
    - scmd_services is defined

- name: 'volume directories: {{ scmd_service_name }}'
  debug:
    msg: '{{ scmd_volume_dirs }}'
  when:
    - ansible_check_mode
