---
- name: 'create directories for domains nginx provision: {{ vhost_uri }}'
  file:
    name: '{{ nginx_domains_full_dir }}'
    state: directory
    owner: '{{ service_user }}'
    group: '{{ service_group }}'
  when:
    - vhost_uri is defined

- name: 'create directories for paths nginx provision: {{ vhost_uri }}'
  file:
    name: '{{ nginx_paths_full_dir }}'
    state: directory
    owner: '{{ service_user }}'
    group: '{{ service_group }}'
  when:
    - vhost_uri is defined
    - vhost_path_name is defined

- name: 'create directories for paths nginx provision upstream: {{ vhost_uri }}'
  file:
    name: '{{ nginx_upstream_full_dir }}'
    state: directory
    owner: '{{ service_user }}'
    group: '{{ service_group }}'
  when:
    - vhost_uri is defined
    - vhost_path_name is defined
    - vhost_upstream is defined

- name: provision base nginx.conf
  template:
    src: '{{ vhost_base_conf_template }}'
    dest: '{{ nginx_volumes_full_dir }}/nginx.conf'
    owner: '{{ service_user }}'
    group: '{{ service_group }}'
  notify:
    - reload nginx
