---
- name: combine ranger configuration
  ansible.builtin.set_fact:
    ranger: '{{ _ranger | combine(ranger, recursive=True) }}'

- name: install ranger
  become: true
  ansible.builtin.package:
    name: ranger
    state: present
  register: install_ranger
  ignore_errors: true
