---
# Molecule configuration for testing cenk1cenk2.reloaded.load_vars plugin
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: podman

platforms:
  - name: instance
    image: quay.io/ansible/creator-ee:latest
    pre_build_image: true
    command: ""
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    privileged: false
    security_opts:
      - label=disable

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks,timer
      stdout_callback: yaml
  inventory:
    host_vars:
      instance:
        ansible_python_interpreter: /usr/bin/python3
  playbooks:
    converge: converge.yml
    prepare: prepare.yml
    verify: verify.yml

verifier:
  name: ansible
