---
- name: stop and remove containers
  shell:
    cmd: docker-compose stop && docker-compose rm -f
    chdir: '{{ scmd_service_dir }}'
  ignore_errors: yes
  when:
    - scmd_state is defined
    - (scmd_state.setup is defined and scmd_state.setup == "absent") or (scmd_state.all is defined and scmd_state.all == "absent")

- name: remove docker setup
  file:
    path: '{{ item }}'
    state: absent
  when:
    - scmd_state is defined
    - scmd_state.setup is defined
    - scmd_state.setup == "absent"
  with_items:
    - '{{ scmd_full_env_dir }}'
    - '{{ scmd_full_build_dir }}'
    - '{{ scmd_service_dir }}/docker-compose.yml'

- name: remove persistent docker volumes
  file:
    path: '{{ item }}'
    state: absent
  when:
    - scmd_state is defined
    - scmd_state.all is defined
    - scmd_state.all == "absent"
  with_items:
    - '{{ scmd_full_logs_dir }}'
    - '{{ scmd_full_volume_dir }}'
    - '{{ scmd_service_dir }}'
