---
- name: register env var files
  set_fact:
    scmd_env_files: "{{ scmd_env_files | default([ ]) + [ { 'name': item[:-3] | basename, 'path': item } ] }}"
  with_fileglob:
    - '{{ scmd_env_file_template_dir }}/*.j2'

- name: debug
  debug:
    msg: '{{ scmd_env_files }}'
  when: ansible_check_mode

- name: register volume dirs
  set_fact:
    scmd_volume_dirs: |
      {% if 'volumes' in item and scmd_volume_dir in item.volumes %}
      {% set value = (scmd_volume_dirs | default([ ]) + [ '%s/%s' | format(scmd_full_volume_dir, scmd_service_name) ]) | unique %}
      {% else %}
      {% set value = scmd_volume_dirs | default([ ]) %}
      {% endif %}
      {{ value }}
  with_items:
    - '{{ scmd_services }}'
  when:
    - scmd_services is defined

- name: debug
  debug:
    msg: '{{ scmd_volume_dirs }}'
  when: ansible_check_mode
