---
scmd_compose_file_version: 3.9

scmd_compose_file_template: docker-compose-v{{ scmd_compose_file_version }}.j2

scmd_native_properties:
  - build
  - hostname
  - user
  - ulimits
  - entrypoint
  - command
  - dns
  - ports
  - extra_hosts
  - volumes
  - network_mode
  - networks
  - privileged
  - devices
  - cap_add
  - security_opt
  - depends_on
  - labels
  - scale
  - pid

scmd_volumes_dir_name: volumes
scmd_env_dir_name: env
scmd_logs_dir_name: logs
scmd_build_dir_name: .docker

scmd_env_file_template_dir: files/env
scmd_base_dir: /root/docker

# scmd_registry_url:
# scmd_registry_user:
# scmd_registry_password:

scmd_log_driver: json-file
scmd_log_options:
  max-size: 10m
  max-file: '1'

scmd_docker_sock_volume: /var/run/docker.sock:/var/run/docker.sock:ro
scmd_docker_config_volume: /root/.docker/config.json:/root/.docker/config.json:ro
scmd_timezone_volume: /etc/timezone:/etc/timezone:ro
scmd_localtime_volume: /etc/localtime:/etc/localtime:ro
