---
- name: allow authorized keys to the host
  authorized_key:
    user: '{{ ansible_management_user }}'
    key: '{{ authorized_keys_all_keys | default("") + "\n" + authorized_keys_authorized_keys | default("") }}'
    state: present
    exclusive: true
