---
# nginx debugging
nginx_debug: false

# template files
vhost_base_conf_template: base.j2
vhost_conf_template: domains.j2
vhost_path_template: paths.j2
vhost_upstream_template: upstream.j2

# default ssl configuration
vhost_ssl: true
vhost_ssl_port: 443
vhost_non_ssl: false
vhost_non_ssl_port: 80
vhost_http_redir: true

# default nginx configuration
vhost_additional_ports: false
vhost_main_max_body_size: 4096M
vhost_keepalive_timeout: 5m
vhost_default_mime_type: application/octet-stream

# nginx gzip configuration
vhost_use_gzip: true
vhost_gzip_comp_level: 6
vhost_gzip_vary: 'on'
vhost_gzip_min_length: 1000
vhost_gzip_buffer_count: 16
vhost_gzip_buffer_size: 8k
vhost_gzip_types:
  - text/css
  - text/javascript
  - text/plain
  - text/xml
  - text/x-component
  - application/javascript
  - application/json
  - application/x-javascript
  - application/atom+xml
  - application/xml
  - application/xml+rss
  - font/truetype
  - font/opentype
  - image/svg+xml

# nginx proxy configuration
vhost_proxy_buffer_count: 4
vhost_proxy_response_buffer_size: 256k
vhost_proxy_header_buffer_size: 128k
vhost_proxy_busy_buffer_size: 256k
vhost_proxy_temp_file_write_size: 256k
vhost_proxy_read_timeout: 600s
vhost_proxy_connect_timeout: 600s

# nginx cache configuration
vhost_proxy_cache_enable: false
vhost_proxy_cache_path: '{{ nginx_cache_path }}'
vhost_proxy_cache_max_size: 100m
vhost_proxy_keys_zone_size: 20m
vhost_proxy_cache_inactive_timeout: 10m
vhost_proxy_cache_key_base: $scheme$proxy_host$uri$is_args$args # see http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_key

vhost_large_client_headers_chucks: 4
vhost_large_client_headers_size: 64k

nginx_ssl_profile: modern

nginx_ssl_protocols:
  modern: TLSv1.2 TLSv1.3
  legacy: TLSv1.2
nginx_ssl_ciphers:
  modern: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
  legacy: ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS

# nginx permission control
nginx_service_name: nginx
nginx_service_user: nginx
nginx_service_group: nginx

# vhost containers
nginx_docker_service_name: nginx-reverse-proxy
letsencrypt_docker_service_name: certbot

# vhost container directory configuration
nginx_paths_dir: paths
nginx_upstream_dir: upstream
nginx_domains_dir: domains
nginx_publish_dir: publish

# nginx internal configuration for paths
nginx_log_dir: /var/log/nginx
nginx_cache_path: /var/cache/nginx

# logging control
vhost_main_access_logs_format: |-
  default escape=json '{'
    '"msec": "$msec", ' # request unixtime in seconds with a milliseconds resolution
    '"connection": "$connection", ' # connection serial number
    '"connection_requests": "$connection_requests", ' # number of requests made in connection
    '"pid": "$pid", ' # process pid
    '"request_id": "$request_id", ' # the unique request id
    '"request_length": "$request_length", ' # request length (including headers and body)
    '"remote_addr": "$remote_addr", ' # client IP
    '"remote_user": "$remote_user", ' # client HTTP username
    '"remote_port": "$remote_port", ' # client port
    '"time_local": "$time_local", '
    '"time_iso8601": "$time_iso8601", ' # local time in the ISO 8601 standard format
    '"request": "$request", ' # full path no arguments if the request
    '"request_uri": "$request_uri", ' # full path and arguments if the request
    '"args": "$args", ' # args
    '"status": "$status", ' # response status code
    '"body_bytes_sent": "$body_bytes_sent", ' # the number of body bytes exclude headers sent to a client
    '"bytes_sent": "$bytes_sent", ' # the number of bytes sent to a client
    '"http_referer": "$http_referer", ' # HTTP referer
    '"http_user_agent": "$http_user_agent", ' # user agent
    '"http_x_forwarded_for": "$http_x_forwarded_for", ' # http_x_forwarded_for
    '"http_host": "$http_host", ' # the request Host: header
    '"server_name": "$server_name", ' # the name of the vhost serving the request
    '"request_time": "$request_time", ' # request processing time in seconds with msec resolution
    '"upstream": "$upstream_addr", ' # upstream backend server for proxied requests
    '"upstream_connect_time": "$upstream_connect_time", ' # upstream handshake time incl. TLS
    '"upstream_header_time": "$upstream_header_time", ' # time spent receiving upstream headers
    '"upstream_response_time": "$upstream_response_time", ' # time spend receiving upstream body
    '"upstream_response_length": "$upstream_response_length", ' # upstream response length
    '"upstream_cache_status": "$upstream_cache_status", ' # cache HIT/MISS where applicable
    '"ssl_protocol": "$ssl_protocol", ' # TLS protocol
    '"ssl_cipher": "$ssl_cipher", ' # TLS cipher
    '"scheme": "$scheme", ' # http or https
    '"request_method": "$request_method", ' # request method
    '"server_protocol": "$server_protocol", ' # request protocol, like HTTP/1.1 or HTTP/2.0
    '"pipe": "$pipe", ' # "p" if request was pipelined, "." otherwise
    '"gzip_ratio": "$gzip_ratio", '
    '"http_cf_ray": "$http_cf_ray"'
    '}'
vhost_main_access_logs: '{{ nginx_log_dir }}/access.log {{ " default" if vhost_main_access_logs_format is defined else "" }}'
vhost_main_error_logs: '{{ nginx_log_dir }}/error.log{{ " debug" if nginx_debug else "" }}'

# letsencrypt configuration
vhost_ssl_le: true
letsencrypt_cert_dir: /etc/letsencrypt
letsencyrpt_container_acme_root: /var/www/certbot
vhost_ssl_domain: '{{ vhost_uri }}'
vhost_ssl_bundle_file: '{{ letsencrypt_cert_dir }}/live/{{ vhost_ssl_domain }}/fullchain.pem'
vhost_ssl_key_file: '{{ letsencrypt_cert_dir }}/live/{{ vhost_ssl_domain }}/privkey.pem'

# openresty opt-in feature
vhost_openresty: false

# openresty session configuration
openresty_enable_session: false
openresty_enable_cookie_session: false
openresty_enable_redis_session: false
openresty_redis_session_host: nginx-reverse-proxy-redis-session

# openresty oauth configuration
openresty_enable_oauth: false
openresty_oauth_redirect_url: /.oauth/callback
openresty_oauth_logout_url: /.oauth/logout
openresty_oauth_redirect_after_logout_path: /
openresty_oauth_scope: openid email profile offline_access
openresty_oauth_ssl_verify: 'no'
openresty_oauth_disable_cache: false
openresty_oauth_session_contents:
  - id_token
  # - user
  # - access_token
