---
- name: reset conditions
  set_fact:
    github_latest_release_existing_version: null
    gitlab_latest_release_up_to_date: null

- name: 'check version for existing binary: {{ github_latest_release_repo }}'
  shell: '{{ github_latest_release_check_version_command }}'
  ignore_errors: true
  changed_when: false
  register: github_latest_release_check_result
  when:
    - github_latest_release_check_version_command is defined

- name: 'set existing version of the binary: {{ github_latest_release_repo }}'
  set_fact:
    github_latest_release_existing_version: '{{ github_latest_release_existing_version | default(github_latest_release_check_result.stdout_lines) }}'
  when:
    - github_latest_release_check_result is defined

- name: 'binary is up to date: {{ github_latest_release_repo }}'
  set_fact:
    gitlab_latest_release_up_to_date: true
  when:
    - github_latest_release_existing_version is defined
    - github_latest_release_existing_version == github_latest_release_final_version
