- name: create env directory
  file:
    name: '{{ scmd_full_env_dir }}'
    state: directory
    owner: '{{ service_user }}'
    group: '{{ service_group }}'

- name: copy env files
  template:
    src: '{{ scmd_docker_env_template.src }}'
    dest: '{{ scmd_full_env_dir }}/{{ scmd_docker_env_template.dest }}.env'

- name: set env fact for scmd_docker
  set_fact:
    scmd_docker_env_template_files: '{{ (scmd_docker_env_template_files | default([ ]) + [ scmd_docker_env_template.dest ]) | unique }}'
